feat: pdf crafter
jina-ai/executor-pdf-crafter pull request #1
Opened 2021-06-24 22:27 UTC by Yongxuanzhang

2021-06-24 22:34 UTC, JoanFM requested changes

2021-06-24 22:34 UTC, JoanFM commented on pdf_crafter.py
> +            logger.error(f'Failed to open due to: {ex}')
instantiate new JinaLogger, do not use default logger. Core Jina has nothing to do with these logs

2021-06-24 22:35 UTC, JoanFM submitted a review, later dismissed

2021-06-24 22:35 UTC, JoanFM commented on pdf_crafter.py
> +                doc.chunks += [Document(text=t, mime_type='text/plain') for t in texts]
doc chunks append

2021-06-24 22:43 UTC, Yongxuanzhang commented on pdf_crafter.py
> +            logger.error(f'Failed to open due to: {ex}')
how about now?

2021-06-24 22:43 UTC, Yongxuanzhang commented on pdf_crafter.py
> +                doc.chunks += [Document(text=t, mime_type='text/plain') for t in texts]
fixed

2021-06-30 07:27 UTC, CatStark commented on README.md
> +
What is that "%EF%B8%8F" in the example?

2021-06-30 07:27 UTC, CatStark commented on README.md
> +1. Install the `executor-pdf-crafterR` package.
Last letter should be lower case right?

2021-06-30 08:28 UTC, slettner commented on README.md
>  #### using source codes
The `using source codes` section looks very similar to the above two snippets. I would remove it, as I see it, it does not provide any good insights

2021-06-30 08:30 UTC, slettner commented on pdf_crafter.py
> +        :param docs: Array of Documents.
```suggestion
        :param docs: DocumentArray containing images
        :param parameters: dictionary to define the `traversal_paths` and the `batch_size`. For example,
               `parameters={'traversal_paths': ['r'], 'batch_size': 10}`.
        :param kwargs: Additional key value arguments.
```

2021-06-30 08:33 UTC, slettner commented on pdf_crafter.py
> +    Text is further split by linebreaks and stored on chunk-chunk level ('cc')
This is not happening in the Crafter. Not sure if we should add it

2021-06-30 08:37 UTC, slettner commented on pdf_crafter.py
> +    def _tag_with_root_doc_id(self, doc: Document, level: str):
I would remove `_tag_with_root_doc_id`. Not really clear why we need this here (I know where it came from, but seeing the Crafter isolated it is hard to understand what the intention of this function is)

2021-06-30 08:52 UTC, slettner commented on tests/integration/test_exec.py
> +def doc_generator(uri, buffer):
You could turn this into a fixture that returns a Generator. Maybe collapse it with the `input_pdf` fixture.
I can be used in the unit test as well then.

2021-06-30 08:55 UTC, slettner requested changes
The Crafter needs some changes I think, tests are looking good. Great Job! 
Let's get this done and merged.

2021-07-02 15:44 UTC, Yongxuanzhang commented on README.md
> +
this is from the template, seems it could still work?

2021-07-02 15:44 UTC, Yongxuanzhang commented on README.md
> +1. Install the `executor-pdf-crafterR` package.
yes, thanks!

2021-07-02 15:47 UTC, Yongxuanzhang commented on README.md
>  #### using source codes
it's different I think. using source codes means pull the code and use the code, the user need to install requirements. Previous snippet is about using docker from hub

2021-07-02 15:49 UTC, Yongxuanzhang commented on pdf_crafter.py
> +    Text is further split by linebreaks and stored on chunk-chunk level ('cc')
yes removed. this is a copy-paste from our example repo. I should have checked the docstrings.

2021-07-02 15:50 UTC, Yongxuanzhang commented on pdf_crafter.py
> +    def _tag_with_root_doc_id(self, doc: Document, level: str):
ok I removed it

2021-07-02 15:51 UTC, Yongxuanzhang commented on tests/integration/test_exec.py
> +def doc_generator(uri, buffer):
good point, thanks

2021-07-04 15:11 UTC, nan-wang requested changes, later dismissed

2021-07-04 15:11 UTC, nan-wang commented on README.md
> +
It is safely to delete this part and let the `toc.yml` from the Github Actions to generate them automatically

2021-07-05 08:40 UTC, slettner commented on README.md
>  #### using source codes
Ah ok, I thought it was just another docker file used in the same way as from the hub.

2021-07-05 08:43 UTC, slettner approved these changes
Looks good from my side.

2021-07-05 11:40 UTC, Yongxuanzhang commented on README.md
> +
sure ， that's awesome

2021-07-05 12:35 UTC, merged